version: 1

formatters:
  standard:
    format: '%(asctime)s [%(levelname)s] %(name)s: %(message)s'


handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  info_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: standard
    filename: ./logs/info/info.log
    maxBytes: 10485760
    backupCount: 10
    encoding: utf-8

  error_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: standard
    filename: ./logs/error/error.log
    maxBytes: 10485760
    backupCount: 10
    encoding: utf-8



root:
  level: DEBUG
  handlers: [console,info_handler,error_handler]


